keys:
  - &admin_daniel age1lw0uetqnw87rxwrvpd7vjrm0zuhcljkln27rek746q3leqf9dfsqnalt30
creation_rules:
  - path_regex: hosts/MacbookAir.fritz.box/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_daniel

