glab: ENC[AES256_GCM,data:++ZHNOl/hMigZaW4MOKD6TSIOEotMG0hxfisPx0DE2a+Jh/Hvmh6nM9VTYdDebCfzq0yMBru/rjQraLZUDFXMTF2VfHWRjZKNy3NFPBYnIIzpI/UlGvjnh7sX+P86LLPUjqA5k6i/kZv0h4Llco7H6v4mXxiT9K/5n34vY/apr7XhgfaYg==,iv:fJN39s99uAW1JUMUqxG8s2fUgzTJGC3PH5M6Ms4ZNhk=,tag:byZArOaLnRAxM8WQ1eUDKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lnnxnx32fhkzr8ukyvaw3ghtddf9gyujewk4h8kxrn0fzk9ds9jqq9quxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYkNnNFdQQU5GalhucFl1
            dFl2MXUybjk2VXN3bXZ2QWFub1dKeEpsNVRZCi96SWtDN0R5OS9JSjk0NHQzWWs1
            cWlSOUZPRUduZmVuSnEwa1NoQko0NlUKLS0tIHRPd3o3b1EyVDBTNlRpb1NVOFA0
            bEM5VDJIeUd2WFovT05rMThJc3VNdGMKLQ9noxnI+sDoMm2d6YpymGqA0fILOoYr
            /Q5fear1YabSRYCaGHqRhftsdDarDHEn0U7QIXeuXyC2qNQcjE4ydQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-06T08:26:00Z"
    mac: ENC[AES256_GCM,data:skeyNfgIs7phYGkb3sQ+3iB0YNu5KP8mCKLlmNwbuE7TU1xvqcgM63YaNqF3q8kSf7ZZYAngE0a6jmKSkk6LAf/YzG/g0DcA0h+Rzs4+orxDIvBzcM8o5FXGMDVk7JrHjl/dILhVASoUu3E3hnYN4LYOPFRcryKeHFfF4BjfNAQ=,iv:Wn1rxDd68NFwiLEvCdqpCdDrtUJLhDUEVH/xIHVg+aY=,tag:nA1fOfHIjt1TJWi+MYam4w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
