codeberg: ENC[AES256_GCM,data:0mAY1Roq988ZwCiyS8EHryvZ4r0nMb9KjxRxSUqYSUkthEo3hPwsKQL3IZLDs2SmbNR1hZw0bt9z5+m3gA/uaA==,iv:HaiYEKtH+Kh806sO5VX7qmnWqS4NMR0TquV1pwfQRrc=,tag:nbMjQGiE/x6iOtG69OkL7Q==,type:str]
gitlab: ENC[AES256_GCM,data:qVpCsw65+2jkpOFsxKlL+SHty19ZfDriCVywc697z3Meqq/ppHyBeytLL3ZWQi4lyOjngnKyXymveFP46J+q10ECixExXYjHFQ==,iv:cmYHSPhfDaXQYmZlRAQfpclu64Wk90BcDfkcTIKHLSk=,tag:RtdxN9vJLIhHcAe37sS7CA==,type:str]
github: ENC[AES256_GCM,data:k6doTEAufux4o436P7TmsII9YojFVjTz0rGVpoOyAPkInMQFUoHWU7uyYaPdCp8K/qOBQ7r84IDkiiYHRQV+DGWK7us+pYD3xw==,iv:gOP20azgEW1Z0/BR078oGht8Ey3EXIAJ3nLhwza7H9o=,tag:R5YhyGZ9nGHiHySDnKUqPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUXJYRjFQRGVLdDNFT2dn
            b215QUZSUThrcy9Pcnl4UU9vY09pdUdtSFc0CjJ0Rm1iZzlkQWtYNGRuajFydWJL
            WmZZUXB3TmgvN1BjaG9WWEhMcXV3KzQKLS0tIHFUWU1rZFc2NGlzc3QwbVdIOGxx
            ekFsSEZtVEp5K3ZmUjVhRnJwWVlmaWcK0BkL8/FlNlyMn9Yl7pkJiY9UE7esnVoe
            F9fQ8DUgN0XOMbDiWqkUlsoW9A/otvo9piKUoOi47bdWwB2f/XctjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lw0uetqnw87rxwrvpd7vjrm0zuhcljkln27rek746q3leqf9dfsqnalt30
    lastmodified: "2026-08-28T11:59:45Z"
    mac: ENC[AES256_GCM,data:/ah/dFs/ke+EhpVFFmoLd89uUlxJUFFNMJ8wWpWA6iw8Ao9/IEJMza2eMPblbh/iNmB1ZYBulCJD0pgAtR7XXGWnba+eWg/Jx+xnU/GeI/R6z4jgLkb1gnFYDjSvMHGdj4zZktZHlR75P2ek3BqQJVBT8f7TOqZPOyE+4lHrDfw=,iv:wx9omH+ntCydNf3wvnXYOpTbaHMRP/kOZhaMHgG+OEU=,tag:pAZ8exFwCOSu2um2h1Dunw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
