glab: ENC[AES256_GCM,data:dbnyiwqH6/xKH8W6Ei/szjGSE7FeEAS9gG1Z27q9knXMsBimUQumnzXU+nT3z5Uz7mhhZ7OxSnIYTJk/CLtrShgCErdom+YPMYaAuR8LkTUs/ehIvL5XS8tfz+HsHZDczT+atv6q4iIX4DpPXJPSkRYKL4P+NC4Oi5wCFooH8WHtY3+kLQ==,iv:ECfcyu4DwMytrwZkIwjOQymc6mhk3C/fjR1TwrRapmU=,tag:rOby64GF+3k+/muTWMuNkw==,type:str]
sops:
    age:
        - recipient: age1lnnxnx32fhkzr8ukyvaw3ghtddf9gyujewk4h8kxrn0fzk9ds9jqq9quxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYkNnNFdQQU5GalhucFl1
            dFl2MXUybjk2VXN3bXZ2QWFub1dKeEpsNVRZCi96SWtDN0R5OS9JSjk0NHQzWWs1
            cWlSOUZPRUduZmVuSnEwa1NoQko0NlUKLS0tIHRPd3o3b1EyVDBTNlRpb1NVOFA0
            bEM5VDJIeUd2WFovT05rMThJc3VNdGMKLQ9noxnI+sDoMm2d6YpymGqA0fILOoYr
            /Q5fear1YabSRYCaGHqRhftsdDarDHEn0U7QIXeuXyC2qNQcjE4ydQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-12T13:43:49Z"
    mac: ENC[AES256_GCM,data:UISjviEYTZ+uBcpe2u6VoT+LYxv1NTDXkOQtM8XPB1i6QCf5rwe4ePijHGxJf/itAimIT2qanRLbTwr9hBa6lmZwHrAGiIDkpWuaGWRtnROi+uK+N7QLJnSwTz4zTdBgUMiU4GbrpHrfi2CjBv337JLbSALyrqgLOJxH+5moI6s=,iv:6j6j9BKgAsb56g0vd/0oJGkReF2GAN5YWbTZKS/Xb88=,tag:usrT0L7KPDbKe20/HWqvJA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
