work: ENC[AES256_GCM,data:RWMBT1FrA94RGutpznXAAim4NSZ7O2aq89qA292WQU0Ahj6bPK7k+0ICK6YW0FjyPy0X5oCj5LtAN6JfEZt4SjeC7rMl,iv:P4EdQP2xD4SD68BwSBaMJl6kAXJAxDC41Tjf3f1YHLE=,tag:JlLAxChJJUUVZhIe+czwUQ==,type:str]
ghent: ENC[AES256_GCM,data:99otG7pJyuCK8ITlivvRzMWgnNr2Y3zQj1oiLNsoqrqXw84jkQT0BH9lmXKDn0g1E80rq5u0zmIqp6p/bHsB9pgvCnEAmOa0j7GG+J93,iv:8T3O5Xe8lZAonJawKSS+zOiRRJsqpfgB2p2mqeJRgX8=,tag:ki0AC1OlqciniykbgjZ0nQ==,type:str]
workc: ENC[AES256_GCM,data:GbdmNipR6uY7FPYxmD2ictcKJybvz7ftD6dKr8JupdpVtmlCsw9fKooCSYuH5ElYzI8yHPwPSIwDpDljh+rEjN9AMilSScbSKu3O7i24jG7OSvtx9W1K6d1yUJb/zWSAMijXUVMjmwXX44TDCudaq9+P4HhVWfmxwvR7nVI2BFGKDRhVCx3x4R3ssChjHzHqV691mNfjVk3XfIeIOAbRtkxW5x9kVbMVfwX9BJXAVAmeMm4zpcEiwGKra5rWjIpzZbd14exFIjzyjQvDHXFOuEhEsdntNou/xx0UxNMUhpBncYtSkm3h5q7kUjpHf+gQLBwr7+TdK5LtYXrrJS+ur/Z62/3vcd6MQHHwc03GDF3+WFplw5xIhXkr9Y6hk/mXRWpyPEeorOv8i5WTiKSa9zesc48WtEzoXrGc3WNiesK9qziOCbuYeNIhOO3fQ+JzfFNhl8jnng8=,iv:VWliKTvdXAMROsoNUQAvzKNbNURQbW56ED4waE1GKV0=,tag:FOqbPX/yfmd78pEPIp751g==,type:str]
opensource: ENC[AES256_GCM,data:dQO8+/fB0qznMbwgzvU0T2NwzyK3/KmB0WYqN94YXDwXt+KSPDX3tVxn5VmTPt0jPkaSrZttEO/MMl+8Ghwu3VLWshlyAzGIOrkX1hblTV+TAp28/45Ijqk4QPAI3ofPR8JbfNHNlPg=,iv:NKgaS4Y9LQdo3OK7djFJ+1xroNM8Go5u+c3hpSVXUPQ=,tag:oowXwg0TcHviJH8g89CFWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcGlCSlZicHIzYm9hQnp0
            dVJsSnVXTjF6M2o0d3BRRFJRT2J5Rk83V2lnClc5a3YvQXNDMWs5MHpxWkRjWWRz
            VExTUzBpLytjOTBpYW15UzlKR0tjcHMKLS0tIDBPN0RJV1k0NjlpaU9rQlFQNWI0
            K1cwbEcyVmhZaUZ2OW00T3g3ZmxGRzgK03tcNWtLcCtX3neaP1KxidRwUjY9VolB
            vWguaurACZN7e17OZCWF0V+A58QgTdTlmBDAsvxmSrHeLJCgEIIUkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lnnxnx32fhkzr8ukyvaw3ghtddf9gyujewk4h8kxrn0fzk9ds9jqq9quxa
    lastmodified: "2026-06-03T10:48:31Z"
    mac: ENC[AES256_GCM,data:8CQfxX2iNwS5MiXHkuZfwFXAqbw3iD3+4nSkrYTDBa2whhJCXCvvsYuMWXqHQgM0SzSBQxzbjM/aMPvJADCpHIPulX/F+w+ORYjz00JKA3YhZ1LOFQEVEAUsPcXF0VVfm9k3K00WLQiBKyij54/kkZeuqbM4ZE4todilpdxasGc=,iv:CM8Mnnu9VHlQZpx4P4n6aDOlg0aJ5ZRbhPonEPIi0Qo=,tag:GYQC4NMRED2s1e9knw2miA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
