codeberg: ENC[AES256_GCM,data:Jvatm8e1FTEk+Vd81UpGVsqfqrhjSc31JbFI/PBBLnUdBkI7m2hMoKikhWJu/kXBZpkWCzYL79vBlvM1rugjAQ==,iv:g9SdW9I6ycdtKsZzDh5kIKe0uEU4JBnJnd5srXkLwwI=,tag:T5FZltb45ICSOtg/fHNpCw==,type:str]
gitlab: ENC[AES256_GCM,data:z48wODiQDQ5XoitAw68n+TLVIxFIowoFDIValnrUKzl5bpFUeUs5OG46BAcwOgSl07qLPzm8OR4OQ5CgqhDG19K0V3CLA1JtTQ==,iv:IOUQ8NMVg/t0Oo1KvuV6Kv0ScULSkrPaBBSckArD1do=,tag:0kjuD5zJiWIQ+vv11i2CBg==,type:str]
github: ENC[AES256_GCM,data:E3awfQ6tqDrKyr5Kw+84SuC8ioiwqHrSxrT/qwdIrduOCdkN3fuqCoZ0aR7ibq/qU75UkWIqqpplVseZ5oPuWfS4l1YIF3zRLg==,iv:219ZvWx3bAqElFDz9cCVlC0J9I6qbOwKT4xcnh+M/zk=,tag:+g4hNctwrFIFWsDg/Ox8Ig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUXJYRjFQRGVLdDNFT2dn
            b215QUZSUThrcy9Pcnl4UU9vY09pdUdtSFc0CjJ0Rm1iZzlkQWtYNGRuajFydWJL
            WmZZUXB3TmgvN1BjaG9WWEhMcXV3KzQKLS0tIHFUWU1rZFc2NGlzc3QwbVdIOGxx
            ekFsSEZtVEp5K3ZmUjVhRnJwWVlmaWcK0BkL8/FlNlyMn9Yl7pkJiY9UE7esnVoe
            F9fQ8DUgN0XOMbDiWqkUlsoW9A/otvo9piKUoOi47bdWwB2f/XctjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lw0uetqnw87rxwrvpd7vjrm0zuhcljkln27rek746q3leqf9dfsqnalt30
    lastmodified: "2026-08-28T13:04:52Z"
    mac: ENC[AES256_GCM,data:GeQllZ5l8rvg47ZhtH6zgURmf0CtUGe0Epa0Xh+NObMOMOOTGAsTQotXQEuXVhlBwiUsvB8siV2lcljAZfAY7pLQHDyeYyu0NjcSLxtQnW3ztb+eU7g+sb533HKzN/PrNO/nRtcSjoiCeZ2fOZ/V/0ullilpAJdDancwxkSJP5A=,iv:Uukg2EZo0qJywfqmmd9y4Drewa+TT4EV5tIQW4A0B3c=,tag:02tEdWJ8IgpSCDPu3oHXlQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
