work: ENC[AES256_GCM,data:H7iqIgn7Jm8FUiZ+vCs9qniYts9jdmQK321Ai+WgXIq+7ELH7EasyTzq9O45F026wN7g7Iu2ngul2BDQu0Mrng9Py7ot,iv:zRH0ZKtpCtsPTlWUFJL4ziv4wbhQwZqFkE+eu9Daego=,tag:c0heBUVrYTfSGg3nix/M8w==,type:str]
opensource: ENC[AES256_GCM,data:KcI8QaGmv6fyCaebzwQEGlpbHvAZ9KrOl2yyIPSfxhbTYkDJPVFwqH521iTrF1zKqM14YKX3tJM3/w9evzvBZdsyUoic/1XD,iv:4B+HKqvSnWn4IWBvMlGNyVId0x89v26zTGHwPGLxTpo=,tag:1JNjhVoRS8esMneB6Q3T1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lnnxnx32fhkzr8ukyvaw3ghtddf9gyujewk4h8kxrn0fzk9ds9jqq9quxa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcGlCSlZicHIzYm9hQnp0
            dVJsSnVXTjF6M2o0d3BRRFJRT2J5Rk83V2lnClc5a3YvQXNDMWs5MHpxWkRjWWRz
            VExTUzBpLytjOTBpYW15UzlKR0tjcHMKLS0tIDBPN0RJV1k0NjlpaU9rQlFQNWI0
            K1cwbEcyVmhZaUZ2OW00T3g3ZmxGRzgK03tcNWtLcCtX3neaP1KxidRwUjY9VolB
            vWguaurACZN7e17OZCWF0V+A58QgTdTlmBDAsvxmSrHeLJCgEIIUkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-25T13:56:46Z"
    mac: ENC[AES256_GCM,data:QZGd7CuUSPDzYSQQUoYDddQPhm+THh7mwWOem0Jo6sEXILcIZz+qs2acMxms5OV1ymXy76XVG3xwKZe2nqCCHgN7rBZuldNihwBiV2+goCz17MKxHm6WuGNKHY9zDWZ1YacOepLmMyOCmfg8e5l0nWs6BhSnzhvX98uWY2ZXI90=,iv:D0ZCnjk9vn4gw2cDzvJkrFAJosOhuA5DUfi+zMPjrBA=,tag:InGeYDU6SSYSSyVVVh+X3Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
