codeberg: ENC[AES256_GCM,data:OZNwqZeCU5+y9eKHJ4h4iUDQ5TSWmkmZ/UTwtTjufqeM/jineqgVtRtofh7IkDBqoFMrqm4/DSx1AqSqxox4xU+l,iv:LyDAnz0FpDqq/z7PI9VtdZPrb+9BLtWtSxVKDzYP2Y0=,tag:BAFEsQd83R+j+Rdvw7giug==,type:str]
gitlab: ENC[AES256_GCM,data:Ch2Sia6Ap3RAQQnfNCnkb5ouUoGlvmrLpR9eOpgIHUfLx0RnlPA7Hc296ItqB1dq9SO5CqtJSFCvUPAee/bqGc50A38e3ps=,iv:fT2jTnfzkEd4UDsBunuOGMeSR/plrPvFobCnyPUskig=,tag:TQ9h8grexGJ8Dgoi3+PNDw==,type:str]
github: ENC[AES256_GCM,data:iymOePgIKgPCtOth79LUybrBEfkjNaTc6qi0TKApiumnEoFaKETDGYQJ6vSvTTeUHEC6NsP5v/nvub0IQoHIhmxO8hM21V6oGkRdLu0=,iv:/bpT9yAfADdqo31D9a9oEf12sqCdiEkIJufY5DoVK/U=,tag:O9uxcYf9g26a2bzLBuR0dA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lw0uetqnw87rxwrvpd7vjrm0zuhcljkln27rek746q3leqf9dfsqnalt30
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUXJYRjFQRGVLdDNFT2dn
            b215QUZSUThrcy9Pcnl4UU9vY09pdUdtSFc0CjJ0Rm1iZzlkQWtYNGRuajFydWJL
            WmZZUXB3TmgvN1BjaG9WWEhMcXV3KzQKLS0tIHFUWU1rZFc2NGlzc3QwbVdIOGxx
            ekFsSEZtVEp5K3ZmUjVhRnJwWVlmaWcK0BkL8/FlNlyMn9Yl7pkJiY9UE7esnVoe
            F9fQ8DUgN0XOMbDiWqkUlsoW9A/otvo9piKUoOi47bdWwB2f/XctjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-20T12:32:36Z"
    mac: ENC[AES256_GCM,data:J7mGLYRnLrBS2MXnVEK9trqlwpLJNUcCHdUHj27mKqDu3HoLw7cx9RJbfjYbWavn8Qy4xwaZjoVaVAFHt4eGy+3NArDWn7wBxImSbCBANzg9X7+2mrMcUjQSGSIKRtV77AHH1AsUc12+yx2jUHLtsI8fL1KfMcX0FlpIZqbf5UY=,iv:VMvDdMP5FlEWAuwAsnNUGQX2SfDJxm7Zx6AncSMlEAM=,tag:Ua8MNr0hQvlJ1Rxm3iBefg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1

